import logging
import smtplib
from datetime import date
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

from reading_recs.config import GMAIL_USER, GMAIL_APP_PASSWORD, GMAIL_TO
from reading_recs.models import ScoredArticle

log = logging.getLogger(__name__)


def build_html(articles: list[ScoredArticle]) -> str:
    """Build HTML email body for the digest."""
    today = date.today().strftime("%B %d, %Y")

    if not articles:
        return f"""<html><body>
<h2>Reading Recs — {today}</h2>
<p>Nothing notable today. The system ran successfully but no articles passed the quality threshold.</p>
</body></html>"""

    rows = []
    for sa in articles:
        limited_flag = ' <span style="color:#c0392b;font-size:12px;">[limited data]</span>' if sa.article.limited_data else ""

        rows.append(f"""<div style="margin-bottom:24px;padding-bottom:16px;border-bottom:1px solid #eee;">
  <h3 style="margin:0 0 4px 0;"><a href="{sa.article.url}">{sa.article.title}</a></h3>
  <div style="color:#666;font-size:13px;margin-bottom:4px;">{sa.article.source} · {sa.llm_score}/10{limited_flag}</div>
  <div style="color:#333;font-size:14px;">{sa.reason}</div>
</div>""")

    body = "\n".join(rows)
    return f"""<html><body style="font-family:-apple-system,Helvetica,Arial,sans-serif;max-width:600px;margin:0 auto;padding:16px;">
<h2 style="border-bottom:2px solid #333;padding-bottom:8px;">Reading Recs — {today}</h2>
{body}
<p style="color:#999;font-size:12px;margin-top:24px;">Generated by reading_recs</p>
</body></html>"""


def send_email(html: str):
    """Send HTML email via Gmail SMTP."""
    today = date.today().strftime("%B %d, %Y")
    msg = MIMEMultipart("alternative")
    msg["Subject"] = f"Reading Recs — {today}"
    msg["From"] = GMAIL_USER
    msg["To"] = GMAIL_TO
    msg.attach(MIMEText(html, "html"))

    with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
        server.login(GMAIL_USER, GMAIL_APP_PASSWORD)
        server.sendmail(GMAIL_USER, GMAIL_TO, msg.as_string())
    log.info("Email sent to %s", GMAIL_TO)


def build_and_send(articles: list[ScoredArticle]):
    """Build digest HTML and send it."""
    html = build_html(articles)
    if not GMAIL_USER or not GMAIL_APP_PASSWORD:
        log.warning("Gmail credentials not configured — printing digest to stdout")
        print(html)
        return
    send_email(html)
